"""add indexer-state

Revision ID: 1ebeb5d471ad
Revises: 43cd9af0e119
Create Date: 2026-05-29 03:24:06.889024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ebeb5d471ad'
down_revision: Union[str, Sequence[str], None] = '43cd9af0e119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_state',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_block', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_indexer_state'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexer_state')
    # ### end Alembic commands ###
